[package]
name = "nei"
version = "1.0.0"
authors = ["Ronaldo F Morais <sirius.ronaldo@gmail.com>"]
edition = "2024"
description = "NEI — Norton Editor Inspired"
license = "0BSD"
repository = "https://github.com/sirius-ronaldo/nei"
readme = "README.md"
keywords = ["editor", "terminal", "tui", "retro", "linux"]
categories = ["command-line-utilities", "text-editors"]

[dependencies]
crossterm = "0.29"
